home:
    path:  /
    defaults: { _controller: AppBundle:Default:index }
services:
    path:  /services
    defaults: { _controller: AppBundle:Default:services }
gallery:
    path:  /gallery
    defaults: { _controller: AppBundle:Default:gallery }
contact:
    path:  /contact
    defaults: { _controller: AppBundle:Default:contact }
