home:
    path:  /
    defaults: { _controller: AppBundle:Default:index }
services:
    path:  /services
    defaults: { _controller: AppBundle:Default:services }
portfolio:
    path:  /portfolio
    defaults: { _controller: AppBundle:Default:portfolio }
contact:
    path:  /contact
    defaults: { _controller: AppBundle:Default:contact }
    requirements:
        _method:  GET|POST
